trigger:
  - main  # Trigger on changes to the 'main' branch

resources:
  - repo: self  

variables:
  DOCKER_USERNAME: 'joshuatud'  # Your Docker Hub username
  tag: '$(Build.BuildId)'  # Tag the image with the Build ID

stages:
  - stage: Build
    displayName: Build Docker Image
    jobs:
      - job: BuildAndPush
        displayName: Build and Push
        pool:
          vmImage: 'ubuntu-latest'  # Use an Ubuntu agent for Docker
        steps:
          - task: Docker@2
            displayName: Build Docker image
            inputs:
              command: 'build'
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: '$(DOCKER_USERNAME)/docker-app:$(tag)'  # Use the variable

          - task: Docker@2
            displayName: Push Docker image to Docker Hub
            inputs:
              command: 'push'
              containerRegistry: 'TUDProj'  # Your Docker Hub connection name in Azure DevOps
              repository: '$(DOCKER_USERNAME)/docker-app'
              tags: '$(tag)'  # Use the variable


