trigger:
  - main

variables:
  dockerRegistryServiceConnection: 'TUDProj'
  imageName: 'joshuatud/docker-app'

jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'build'
          dockerfile: '**/Dockerfile'
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(imageName)
          tags: 'latest'
      
      - task: Docker@2
        inputs:
          command: 'push'
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(imageName)
          tags: 'latest'
