trigger:
  - main

variables:
  dockerRegistryServiceConnection: 'TUDProj'  
  imageName: 'joshuatud/docker-app'
  azureContainerGroup: 'DefaultResourceGroup-SUK'
  azureRegion: 'uksouth'
  azureResourceGroup: 'DefaultResourceGroup-SUK'
  containerName: 'con-proj'
  containerPort: 5000

jobs:
  - job: BuildAndDeploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'build'
          dockerfile: '**/Dockerfile'
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(imageName)
          tags: 'latest'

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'devopstud'  # Your Azure Service Connection
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az container create \
              --name $(containerName) \
              --resource-group $(azureResourceGroup) \
              --image $(imageName):$(Build.BuildId) \
              --cpu 1 \
              --memory 1.5 \
              --ports $(containerPort) \
              --dns-name-label $(containerName)-$(Build.BuildId) \
              --location $(azureRegion)
          displayName: 'Deploy to Azure Container Instances (ACI)'
