trigger:
  - main  # Trigger on changes to the 'main' branch

resources:
  - repo: self  

variables:
  tag: '$(Build.BuildId)'  

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: BuildAndPush
        displayName: Build and Push
        pool:
          vmImage: 'ubuntu-latest'  # Use an Ubuntu agent for Docker
        steps:
        - task: Docker@2
          displayName: Build Docker image
          inputs:
            command: 'build'
            dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  
            tags: '$(tag)'  

        - task: Docker@2
          displayName: Push Docker image to Docker Hub
          inputs:
            command: 'push'
            containerRegistry: 'DockerHubConnection'  
            repository: 'joshuatud/docker-app'  
            tags: '$(tag)'  

