trigger:
  - main

variables:
  dockerRegistryServiceConnection: 'TUDProj'
  imageName: 'joshuatud/docker-app'
  azureResourceGroup: 'DefaultResourceGroup-SUK'
  azureRegion: 'uksouth'
  containerName: 'con-proj'
  containerPort: 5000

jobs:
  - job: BuildAndDeploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: 'Build Docker Image'
        inputs:
          command: 'build'
          dockerfile: '**/Dockerfile'
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(imageName)
          tags: 'latest'

      - task: Docker@2
        displayName: 'Push Docker Image to ACR'
        inputs:
          command: 'push'
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(imageName)
          tags: 'latest'

      - task: AzureCLI@2
        displayName: 'Deploy to Azure Container Instances (ACI)'
        inputs:
        
