trigger:
  branches:
    include:
      - main   # or master, depending on your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)' # Set this up below
    repository: 'flask-docker-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

# Optional: Push image to a registry if using an external one
- task: Docker@2
  inputs:
    command: 'push'
    containerRegistry: '$(dockerRegistryServiceConnection)' 
    repository: 'flask-docker-app'
    tags: 'latest'
