trigger:
  branches:
    include:
      - main  
pool:
  vmImage: 'ubuntu-latest'  

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'  
    repository: 'docker-app'  
    command: 'buildAndPush'  
    Dockerfile: 'Dockerfile' 
    tags: 'latest'  
