trigger:
  branches:
    include:
      - main   # or master, depending on your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)' # Set this up below
    repository: 'ca2cloud'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

